### ISSUE TITLE
Not working in Angular 14.2

### ISSUE THREAD

**Issue by cmschandan** [chenqingspring/lottie-angular2#96]
Hey Geeks, 
I am trying to install ngx lottie. but it's showing below errors in my application 

`node_modules/ngx-lottie/lib/base.directive.d.ts:69:18 - error TS2707: Generic type 'ɵɵDirectiveDeclaration' requires between 6 and 8 type arguments.

69     static ɵdir: i0.ɵɵDirectiveDeclaration<BaseDirective, "[lottie]", never, { "options": "options"; "containerClass": "containerClass"; "styles": "styles"; }, { "animationCreated": "animationCreated"; "complete": "complete"; "loopComplete": "loopComplete"; "enterFrame": "enterFrame"; "segmentStart": "segmentStart"; "configReady": "configReady"; "dataReady": "dataReady"; "domLoaded": "domLoaded"; "destroy": "destroy"; "error": "error"; }, never, never, false, never>;
                    `
![image](https://user-images.githubusercontent.com/21227329/235146367-f562aad3-9377-4be6-bb6f-428b5df34fbc.png)
